//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.25 at 10:56:38 AM CET 
//


package fr.pantheonsorbonne.cri.instrumentation.impl.jacoco.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "counter")
public class Counter {

    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "missed", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String missed;
    @XmlAttribute(name = "covered", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String covered;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the missed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissed() {
        return missed;
    }

    /**
     * Sets the value of the missed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissed(String value) {
        this.missed = value;
    }

    /**
     * Gets the value of the covered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCovered() {
        return covered;
    }

    /**
     * Sets the value of the covered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCovered(String value) {
        this.covered = value;
    }

}
