//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.25 at 10:56:38 AM CET 
//


package fr.pantheonsorbonne.cri.instrumentation.impl.jacoco.model;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "clazzOrSourcefile",
        "counter"
})
@XmlRootElement(name = "package")
public class Package {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlElements({
            @XmlElement(name = "class", type = Class.class),
            @XmlElement(name = "sourcefile", type = Sourcefile.class)
    })
    protected List<Object> clazzOrSourcefile;
    protected List<Counter> counter;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the clazzOrSourcefile property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazzOrSourcefile property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazzOrSourcefile().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Class }
     * {@link Sourcefile }
     */
    public List<Object> getClazzOrSourcefile() {
        if (clazzOrSourcefile == null) {
            clazzOrSourcefile = new ArrayList<Object>();
        }
        return this.clazzOrSourcefile;
    }

    public List<Class> getClazz() {
        return this.getClazzOrSourcefile().stream().filter(c -> c instanceof Class).map(c -> (Class) c).collect(Collectors.toList());
    }

    public List<Sourcefile> getSourceFile() {
        return this.getClazzOrSourcefile().stream().filter(c -> c instanceof Sourcefile).map(c -> (Sourcefile) c).collect(Collectors.toList());
    }

    /**
     * Gets the value of the counter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the counter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCounter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Counter }
     */
    public List<Counter> getCounter() {
        if (counter == null) {
            counter = new ArrayList<Counter>();
        }
        return this.counter;
    }

}
