// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/requirements.proto

package fr.pantheonsorbonne.cri.model.requirements;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:requirements.Empty)
    com.google.protobuf.MessageOrBuilder {
}
